# Generated by Django 4.0.4 on 2022-05-24 15:14

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('certificate_id', models.IntegerField(primary_key=sqlalchemy.sql.expression.true, serialize=False, verbose_name='certificate_id')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Passports',
            fields=[
                ('passport_id', models.IntegerField(primary_key=sqlalchemy.sql.expression.true, serialize=False, verbose_name='passport_id')),
                ('first_name', models.CharField(max_length=30, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last_name')),
                ('middle_name', models.CharField(max_length=30, verbose_name='middle_name')),
                ('series', models.IntegerField(verbose_name='series')),
                ('passport_number', models.IntegerField(verbose_name='number')),
                ('registration', models.TextField(verbose_name='registration')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=sqlalchemy.sql.expression.true, serialize=False, verbose_name='user_id')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
            ],
        ),
    ]
