# Generated by Django 4.0.4 on 2022-05-24 15:51

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.IntegerField(primary_key=sqlalchemy.sql.expression.true, serialize=False, verbose_name='article_id')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='passport_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mfc.passports', unique=sqlalchemy.sql.expression.true),
            preserve_default=False,
        ),
    ]
