# Generated by Django 4.0.4 on 2022-06-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0003_remove_application_id_application_application_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user_id',
            new_name='user',
        ),
    ]
