# Generated by Django 4.0.4 on 2022-05-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0005_departments_alter_articles_article_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='address',
        ),
        migrations.AddField(
            model_name='departments',
            name='building',
            field=models.IntegerField(null=True, verbose_name='building'),
        ),
        migrations.AddField(
            model_name='departments',
            name='city',
            field=models.CharField(default=1, max_length=20, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departments',
            name='house',
            field=models.IntegerField(default=1, verbose_name='house'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departments',
            name='street',
            field=models.CharField(default=1, max_length=40, verbose_name='street'),
            preserve_default=False,
        ),
    ]
