# Generated by Django 4.0.4 on 2022-06-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0005_rename_certificate_id_application_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passports',
            name='passport_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='passport_id'),
        ),
    ]
