# Generated by Django 4.0.4 on 2022-06-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0006_alter_passports_passport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='passports',
            name='branch',
            field=models.CharField(default=1, max_length=128, verbose_name='branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passports',
            name='branch_number',
            field=models.IntegerField(default=1, verbose_name='branch_number'),
            preserve_default=False,
        ),
    ]
