# Generated by Django 4.0.4 on 2022-06-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0007_articles_author_users_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image_url',
            field=models.TextField(default=1, verbose_name='image_url'),
            preserve_default=False,
        ),
    ]
