# Generated by Django 4.0.4 on 2022-06-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0009_alter_articles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='type',
            field=models.CharField(choices=[('CR', 'Certificate'), ('EX', 'Excerpt')], default='CR', max_length=2),
        ),
    ]
