# Generated by Django 4.0.4 on 2022-06-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0009_alter_articles_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Applications',
        ),
    ]
