# Generated by Django 4.0.4 on 2022-06-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0010_rename_application_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='state',
            field=models.CharField(choices=[('Выполнено', 'Выполнено'), ('Отклонено', 'Отклонено'), ('В процессе', 'В процессе'), ('Принято к рассмотрению', 'Принято к рассмотрению')], default='Принято к рассмотрению', max_length=22),
        ),
    ]
