# Generated by Django 4.0.4 on 2022-06-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0011_alter_certificates_type_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='application',
        ),
    ]
