# Generated by Django 4.0.4 on 2022-06-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0012_remove_applications_application_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='state',
            field=models.CharField(choices=[('Выполнено', 'Выполнено'), ('Отклонено', 'Отклонено'), ('В процессе', 'В процессе'), ('Принято к рассмотрению', 'Принято к рассмотрению'), ('Отменено', 'Отменено')], default='Принято к рассмотрению', max_length=22),
        ),
    ]
