# Generated by Django 4.0.4 on 2022-06-22 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='article_id')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('image_url', models.TextField(verbose_name='image_url')),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('certificate_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='certificate_id')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('type', models.CharField(choices=[('CR', 'Справка'), ('EX', 'Выписка')], default='CR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='department_id')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('street', models.CharField(max_length=40, verbose_name='street')),
                ('house', models.IntegerField(verbose_name='house')),
                ('building', models.IntegerField(null=True, verbose_name='building')),
            ],
        ),
        migrations.CreateModel(
            name='Passports',
            fields=[
                ('passport_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='passport_id')),
                ('first_name', models.CharField(max_length=30, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last_name')),
                ('middle_name', models.CharField(max_length=30, verbose_name='middle_name')),
                ('series', models.IntegerField(verbose_name='series')),
                ('passport_number', models.IntegerField(verbose_name='number')),
                ('registration', models.TextField(verbose_name='registration')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('passport_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mfc.passports', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(verbose_name='application_date')),
                ('certificate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mfc.certificates')),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mfc.departments')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mfc.users')),
            ],
        ),
    ]
