# Generated by Django 4.0.4 on 2022-06-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0002_alter_application_application_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='application_id'),
            preserve_default=False,
        ),
    ]
