# Generated by Django 4.0.4 on 2022-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0008_alter_passports_branch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
    ]
