# Generated by Django 4.0.4 on 2022-06-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0011_applications_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='application_date',
        ),
    ]
